config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'login', to: 'pages#login'
  post '/login', to: 'auth#login'
  get '/logout', to: 'auth#logout'
  get "profile" , to: "pages#profile"
  get 'register', to: 'pages#register'
  get 'invitations', to: 'pages#invitations'
  get 'transactions', to: 'pages#transactions'
  get "new" , to: "pages#newInvitation"
  get 'invitations/:id', to: 'pages#invitationDetail', as: 'invitation_detail'
  get 'export/users', to: 'pages#exportUsers' , as: 'export_users'
  get 'export/roles', to: 'pages#exportRoles' , as: 'export_roles'
  get 'export/resource', to: 'pages#exportResource' , as: 'export_resource'

  resources :invitations, only: [:create]
  resources :sellers, only: [:create]
  resources :transactions, only: [:show], param: :id


  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invitation.rb
class Invitation < ApplicationRecord

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  has_many :transactions
  belongs_to :seller

  # Define the Elasticsearch index configuration
  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :product, analyzer: 'english', index_options: 'offsets'
    end
  end

  def as_indexed_json(_options = {})
  as_json(only: [ :uuid , :product , :description, :price, :store_wilaya, :store_location, :delivery_type, :local_delivery_price, :active, :delivery_delay_hours, :date, :images , :seller_id])
  end

  def self.search_by_default(query)
    __elasticsearch__.search(
      {
        query: {
          match: {
            product: query
          }
        }
      }
    )
  end

end

app/models/seller.rb
class Seller < ApplicationRecord
    has_many :invitations
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :invitation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # des méthodes utiles
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController 

    def login
        if request.post?
            puts "Params: #{params.inspect}"
            seller = Seller.find_by(email: params[:email],password: params[:password])  
            puts "sell #{Seller.find_by(email: params[:email])}"
            if seller 
              session[:user_id] = seller.id
              puts "Sucess"
              redirect_to root_path, notice: 'Login successful!'
            else
              puts "Failed"
              flash[:alert] = 'Invalid email or password'
              redirect_to login_path
            end
          end
    end

    def logout 
      session[:user_id] = ""
      redirect_to login_path
    end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
    def show
      @invitation = Invitation.find(params[:id])
    end

    def create

      puts "Params me: #{params.inspect}"

      # Find the seller using the user_id stored in the session
      seller = Seller.find_by(id: session[:user_id])
  
      # Check if all required fields are present and not empty
      if required_fields_present_and_not_empty?
        # Build a new Invitation associated with the found seller
        @invitation = seller.invitations.build(invitation_params)
  
        if @invitation.save
          redirect_to invitations_path, notice: 'Invitation was successfully created.'
        else
          flash.now[:alert] = "Erreur lors de la création de l'invitation."
          render 'pages/newInvitation'
        end
      else
        flash[:alert] = 'Vous devez remplir tous les champs'
        redirect_to new_path
      end
    end
  
    private
  
    def invitation_params
      params.permit(
    :product, :description, :price, :store_wilaya, :store_location,
    :delivery_type, :local_delivery_price, :delivery_delay_hours, :date, :images
  ).merge(seller_id: params[:seller_id])
    end

    def required_fields_present_and_not_empty?
      required_fields = [:product, :description , :price, :store_wilaya, :store_location, :delivery_type, :local_delivery_price, :date , :images]
      
      required_fields.all? { |field| params[field].present? && params[field].strip.present? }
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  require 'net/http'
  require 'json'


  def home
    @transaction_status_list = [
      {
      title: "Encaissé",
      value: 80,
      color: "44F2A1",
      icon: "fa-solid fa-rectangle-xmark"
    },
    {
      title: "En attente",
      value: 80,
      color: "EEE745",
      icon: "fa-solid fa-circle-pause",
    },
    {
      title: "Annulé",
      value: 80,
      color: "EE4563",
      icon: "fa-solid fa-square-check",
    },
    {
      title: "Verrouillé",
      value: 80,
      color: "0019FF",
      icon: "fa-solid fa-comments-dollar",
    },
    {
      title: "Ce mois",
      value: 80,
      color: "6D6D6D",
      icon: "fa-solid fa-calendar-days",
    },
    ]
    @test =  "Your iPhone 12, iPhone 12 mini, iPhone 12 Pro, or iPhone 12 Pro Max works with the 5G networks of certain carriers. Learn more about 5G. Add and view widgets"
    @invitations = Invitation.all
  end

  def login
  end

  def register
  end

  def invitations
    @invitations = Invitation.all

    puts "inv "
    all_invitations = Invitation.all

    # Print the length of the invitations
    puts "Number of Invitations: #{all_invitations.length}"
  end

  def newInvitation
  
  end

  def invitationDetail
    @invitation = Invitation.find_by(id: params[:id])
    if @invitation.nil?
      redirect_to '/invitations'
    end
    
    @transactions = Transaction.where(invitation_id: params[:id])
    
  end

  def transactions
  end

  def profile
  @seller = Seller.find(session[:user_id])
  end

  def exportUsers
    url = URI.parse('http://localhost:3000/export/user?email=developer@pyx4.com&password=Abcd123456') 
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = (url.scheme == 'https')

    request = Net::HTTP::Get.new(url)
    response = http.request(request)

    if response.code == '200'
      @data = JSON.parse(response.body)
    else
      @error_message = "Failed to fetch data. HTTP Status: #{response.code}"
    end
  end

  def exportRoles
    url = URI.parse('http://localhost:3000/export/role?email=developer@pyx4.com&password=Abcd123456') 
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = (url.scheme == 'https')

    request = Net::HTTP::Get.new(url)
    response = http.request(request)

    if response.code == '200'
      @data = JSON.parse(response.body)
    else
      @error_message = "Failed to fetch data. HTTP Status: #{response.code}"
    end
  end

  def exportResource 
    url = URI.parse('http://localhost:3000/export/resource?email=developer@pyx4.com&password=Abcd123456') 
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = (url.scheme == 'https')

    request = Net::HTTP::Get.new(url)
    response = http.request(request)

    if response.code == '200'
      @data = JSON.parse(response.body)
    else
      @error_message = "Failed to fetch data. HTTP Status: #{response.code}"
    end
  end



end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController


      def create 
        puts "parms: #{seller_params}"
        @seller = Seller.find(params[:id])
        @seller.assign_attributes(seller_params)
        if @seller.save
          redirect_to profile_path , notice: 'Seller was successfully updated.'
        else
            flash.now[:alert] = "Erreur lors de la modification de profile"
            render 'pages/profile'
        end
      end
    
      private
    
      def set_seller
        @seller = Seller.find(params[:id])
      end


    
      def seller_params
        params.permit(:id ,:name, :phoneNumber, :email, :firstName, :businessName, :location, :wilaya, :description, :rib)
      end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    def show
      @transaction = Transaction.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index  # GET "users/"
       @users = User.all
     end
   
     def show
       # GET "users/:id"
     end
   
   
     def create 
       @user = User.new(user_params)
     end
   
   
     def update # PATCH "users/:id"
       @user.update(user_params)
     end
   
     def destroy  # DELETE "users/:id"
       @user.destroy
     end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/seller_helper.rb
module SellerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Markert</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "partial", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
      <link
      rel="stylesheet"
      type="text/css"
      href="//fonts.googleapis.com/css?family=Josefin+Sans"
    />
    <style>
      body {
        font-family: "Josefin Sans";
      }
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/exportResource.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Page Title</title>
  <%= stylesheet_link_tag 'invitation_detail', media: 'all' %>
  <!-- Other meta tags, stylesheets, or scripts specific to this view -->
</head>
<body>
<%= render "partials/navbar" %>
    <div class="export-page" >
        <div class="export-page-content">
        <br />
                  <div class="export-list">
            <div class="header" >
              <span>Titre</span>
              <span>Description</span>
              <span>Date de création</span>
              <span>Tags</span>
              <span>Type </span>
              <span>URL</span>
            </div>
         <% @data["data"].each do |tr| %>              
              <div class="transaction-item">
              <span><%= tr["Titre"]  %></span>
              <span><%= tr["Description"]%></span>
              <span><%= tr["Date de création"] %></span>
              <span ><%= tr["Tags"] %></span>
              <span><%= tr["Type"] %></span>
              <span><%= tr["URL"] %></span>
              </div>
            <% end %>
        </div>
      </div>
    </div>
</body>
</html>

app/views/pages/exportRoles.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Page Title</title>
  <%= stylesheet_link_tag 'invitation_detail', media: 'all' %>
  <!-- Other meta tags, stylesheets, or scripts specific to this view -->
</head>
<body>
<%= render "partials/navbar" %>
    <div class="export-page" >
        <div class="export-page-content">
        <br />
                  <div class="export-list">
            <div class="header" >
              <span>Titre</span>
              <span>Description</span>
              <span>Date de création</span>
              <span>Tags</span>
              <span>Status </span>
              <span>Utilisateurs</span>

            </div>
         <% @data["data"].each do |tr| %>              
              <div class="transaction-item">
              <span><%= tr["Titre"]  %></span>
              <span><%= tr["Description"]%></span>
              <span><%= tr["Date de création"] %></span>
              <span ><%= tr["Tags"] %></span>
              <span><%= tr["Status"] %></span>
              <span><%= tr["Utilisateurs"] %></span>
              </div>
            <% end %>
        </div>
      </div>
    </div>
</body>
</html>

app/views/pages/exportUsers.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Page Title</title>
  <%= stylesheet_link_tag 'invitation_detail', media: 'all' %>
  <!-- Other meta tags, stylesheets, or scripts specific to this view -->
</head>
<body>
<%= render "partials/navbar" %>
    <div class="export-page" >
        <div class="export-page-content">
        <br />
                  <div class="export-list">
            <div class="header" >
              <span>Name</span>
              <span>mobile phone</span>
              <span>roles</span>
              <span>service</span>
              <span>gendre </span>
              <span>language</span>
              <span>URL</span>
            </div>
         <% @data["data"].each do |tr| %>              
              <div class="transaction-item">
              <span><%= tr["lastname"]  %> <%= tr["firstname"]  %></span>
              <span><%= tr["mobile_phone"]%></span>
              <span><%= tr["roles"] %></span>
              <span ><%= tr["service"] %></span>
              <span><%= tr["gender"] %></span>
              <span><%= tr["language"] %></span>
              <span><%= tr["URL"] %></span>
              </div>
            <% end %>
        </div>
      </div>
    </div>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Page Title</title>
  <%= stylesheet_link_tag 'home', media: 'all' %>
  <!-- Other meta tags, stylesheets, or scripts specific to this view -->
</head>
<body>
  <%= render "partials/navbar" %>
  <div class="home-page">

      <div class="header">
        <div class="rip-container">
          <div class="title">Total des encaissements / ventes</div>
          <div class="content">
            <div class="price">29040.00 DZD</div>
            <div class="rip-id">
              <span>PT 3900 7599 4678 5688</span>
            </div>
          </div>
        </div>
        <div class="content">
          <div class="title">Transactions : </div>
          <div class="list">
            <% @transaction_status_list.each do |it| %>
                <div style="background-color: #<%= it[:color] %>44" class="status">
                 <div class="label">
                    <div class="icon"><i class="<%= it[:icon] %>"></i></div>
                    <span><%= it[:title] %></span>
                </div>
                <div style="color: ##{it[:color]};" class="value">
                    <%= it[:value] %>
                </div>
                </div>
            <% end %>
          </div>
            <br />
          <div class="title">
            Invitation Récentes <a href="/invitations" class="tous" >voir tous</a>
          </div>
          
                <% @invitations.each do |it| %>
                <%= render "partials/invitationCard", inv: it %>
                 <% end %>
        </div>
      </div>
    </div>
</body>
</html>

app/views/pages/invitationDetail.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Page Title</title>
  <%= stylesheet_link_tag 'invitation_detail', media: 'all' %>
  <!-- Other meta tags, stylesheets, or scripts specific to this view -->
</head>
<body>
<%= render "partials/navbar" %>
  <div class="invitation-page">
              <div class='invitation-page-header'>
          <div class="header-page">
      <div class="header-left">
        <div class="title">Annonce <%= @invitation.uuid %> </div>
        <div class="descr">Tous les information et les transactio de cette announce</div>
      </div>


        <div class="header-right">
          <div id="search-icon-container" class="search-icon-container">
            +
          </div>
          <div class="search-bar-container">
            <input
              name="search"
              placeholder="Search by name"
              id="searchInput"
            />
          </div>
        </div>
    </div>
      </div>
        <div class="invitation-page-content">
          <%= render "partials/invitationCard", inv: @invitation %>
          <br />
          <div class="transaction-list">
            <div class="header" >
              <span>code transaction</span>
              <span>date de création</span>
              <span>État</span>
              <span>Prix de laivraison</span>
              <span>date de payment</span>
              <span>livraison</span>
            </div>
         <% @transactions.each do |tr| %>              
              <div class="transaction-item">
              <span><%= tr.id %></span>
              <span><%= tr.created_at%></span>
              <span ><%= tr.state %></span>
              <span><%= tr.delivery_price%></span>
              <span><%= tr.payment_date %></span>
              <span><%= tr.delivery_place%></span>
              </div>
            <% end %>
        </div>
      </div>
</body>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    console.log("sksndlcksn")
    const searchInput = document.getElementById("searchInput");
    const searchDiv = document.getElementById("search-icon-container");

    // Add an event listener to the div
    searchDiv.addEventListener("click", function () {
      const inputValue = searchInput.value;
    console.log("mfl;")
      // Update the window location based on the input value
      window.location.href = "/invitations/search/" + inputValue;
    });
  });
</script>
</html>

app/views/pages/invitations.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Page Title</title>
  <%= stylesheet_link_tag 'invitations', media: 'all' %>
  <!-- Other meta tags, stylesheets, or scripts specific to this view -->
</head>
<body>
<%= render "partials/navbar" %>
  <div class='invitations-page'>
      <div class='invitation-page-header'>
          <div class="header-page">
      <div class="header-left">
        <div class="title">Announces</div>
        <div class="descr">List de tous les anounces</div>
      </div>


        <div class="header-right">
          <div id="search-icon-container" class="search-icon-container">
            +
          </div>
          <div class="search-bar-container">
            <input
              name="search"
              placeholder="Search uuid"
              id="searchInput"
            />
          </div>
        </div>
    </div>
      </div>
      <div>
      <a href="<%= new_path %>" class='new-invitation' >
        <div class='icon-container'>
          +
        </div>
        <div onClick={navigateToNewInvitation} class='title' >Ajouter une nouvelle Invitation !</div>
      </a>
      </div>
      <div class='invitations-list'>
                  <% @invitations.each do |it| %>
                  <a href="/invitations/<%= it.id %> ">
                <%= render "partials/invitationCard", inv: it %>
                 </a>
                 <% end %>
                


      </div>  
    </div>
</body>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const searchInput = document.getElementById("searchInput");
    const searchDiv = document.getElementById("search-icon-container");

    // Add an event listener to the div
    searchDiv.addEventListener("click", function () {
      const inputValue = searchInput.value;

      // Update the window location based on the input value
      window.location.href = "/invitations/" + inputValue;
    });
  });
</script>
</html>

app/views/pages/invitationsSearch.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Page Title</title>
  <%= stylesheet_link_tag 'invitations', media: 'all' %>
  <!-- Other meta tags, stylesheets, or scripts specific to this view -->
</head>
<body>
<%= render "partials/navbar" %>
  <div class='invitations-page'>
      <div class='invitation-page-header'>
          <div class="header-page">
      <div class="header-left">
        <div class="title">Announces</div>
        <div class="descr">List de tous les anounces</div>
      </div>
        <div class="header-right">
          
        </div>
    </div>
      </div>
      <div>
      <a href="<%= new_path %>" class='new-invitation' >
        <div class='icon-container'>
          +
        </div>
        <div onClick={navigateToNewInvitation} class='title' >Ajouter une nouvelle Invitation !</div>
      </a>
      </div>
      <div class='invitations-list'>
                  <% @invitations.each do |it| %>
                  <a href="/invitations/<%= it.id %> ">
                <%= render "partials/invitationCard", inv: it %>
                 </a>
                 <% end %>
                 <% if @invitations.length == 0 %>
                     <div>No invitations found</div>
                  <% end %>

                
      </div>  
    </div>
</body>
<script>
  
</script>
</html>

app/views/pages/login.html.erb
<!-- app/views/your_controller_name/your_view_name.html.erb -->

<!DOCTYPE html>
<html>
<head>
  <title>Your Page Title</title>
  <%= stylesheet_link_tag 'login', media: 'all' %>
  <!-- Other meta tags, stylesheets, or scripts specific to this view -->
</head>
<body>
  <!-- Your page content -->
  <div class="login-page">
      <div class="login-picture">
        <img src="<%= asset_path('PPP.png') %>" />
      </div>
      <div class="login-content">
        <div class="body">
          <div class="title">Bienvenue à pay part</div>
          <div class="title">Connectez-vous pour continuer</div>
        <% if flash[:alert].present? %>
            <div class="error">
                <%= flash[:alert] %>
            </div>
        <% end %>
          <form method="post" action="/login" class="pay-part-form">
             <div class="pay-part-form-container vertical" >
            <div class="field-container" >
              <label class="label" >
                Email
              </label>
                <input
                  class="field"
                  type="email"
                  id="email"
                  name="email"
                />
            </div>
            <div class="field-container">
              <label class="label" >
                Mot de passe
              </label>
                <input
                  class="field"
                  type="password"
                  id="password"
                  name="password"
                />
            </div>
        </div>


          <button  class="submit-form" type="submit">
            Envoyer
          </button>



      </form>
          <div  class="sub-title">
          vous n'avez pas un compte ?
          </div>
        </div>
      </div>
    </div>
</body>
</html>

app/views/pages/profile.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Page Title</title>
  <%= stylesheet_link_tag 'profile', media: 'all' %>
  <!-- Other meta tags, stylesheets, or scripts specific to this view -->
</head>
<body>
  <%= render "partials/navbar" %>
        <div class="profile-page">
        <div class="header">
          <div class="title">Modifier Profile</div>
        </div>
        <div class="content">
          <div class="new-profile-card">
          <% if flash[:alert].present? %>
            <div class="error-generale">
                <%= flash[:alert] %>
            </div>
        <% end %>

            <form class="pay-part-form"  action="<%= sellers_path %>" method="post" >


              <%= hidden_field_tag :id, session[:user_id] %>
              <div class="pay-part-form-container">
                <div class="form-header">
                  <div class="title">
                    <div class="icon-container">
                      <i class="fa-solid fa-user"></i>
                    </div>
                    <span>Informations personnels</span>
                  </div>

                
                </div>

                <div class="field-container" >
                  <label class="label" htmlFor={field.name}>
                    nom
                  </label>

                  <input
                    class="field"
                    type="text"
                    id="name"
                    name="name"
                    value="<%= @seller.name %>"
                  />
                </div>
                <div class="field-container" >
                  <label class="label" htmlFor={field.name}>
                    Prénom
                  </label>

                  <input
                    class="field"
                    type="text"
                    id="firstName"
                    name="firstName"
                     value="<%= @seller.firstName %>"
                  />
                </div>

                                <div class="field-container" >
                  <label class="label" htmlFor={field.name}>
                    Email
                  </label>

                  <input
                    class="field"
                    type="text"
                    id="email"
                    name="email"
                     value="<%= @seller.email %>"
                  />
                </div>

                <div class="field-container" >
                  <label class="label" htmlFor={field.name}>
                    Numéro de téléphone
                  </label>

                  <input
                    class="field"
                    type="number"
                    id="phoneNumber"
                    name="phoneNumber"
                    value="<%= @seller.phoneNumber %>"
                  />
                </div>
                <div class="field-container" >
                  <label class="label" htmlFor={field.name}>
                    RIB / RIP
                  </label>

                  <input
                    class="field"
                    type="text"
                    id="rib"
                    name="rib"
                    value="<%= @seller.rib %>"
                  />
                </div>


                <div class="form-header">
                  <div class="title">
                    <div class="icon-container">
                      <i class="fa-solid fa-business-time"></i>
                    </div>
                    <span>Informations sur l'entreprise</span>
                  </div>

                  <div class="sub-title"></div>
                </div>

                <div class="field-container" >
                  <label class="label" htmlFor={field.name}>
                    Nom de l'entreprise
                  </label>

                  <input
                    class="field"
                    type="text"
                    id="businessName"
                    name="businessName"
                    value="<%= @seller.businessName %>"
                  />
                </div>

                <div class="field-container" >
                  <label class="label" htmlFor={field.name}>
                    Description
                  </label>

                  <input
                    class="field"
                    type="text"
                    id="description"
                    name="description"
                    value="<%= @seller.description %>"
                  />
                </div>
                <div class="field-container" >
                  <label class="label" htmlFor={field.name}>
                    Magasin wilaya
                  </label>

                  <input
                    class="field"
                    type="text"
                    id="wilaya"
                    name="wilaya"
                    value="<%= @seller.wilaya %>"
                  />
                </div>
                 <div class="field-container" >
                  <label class="label" htmlFor={field.name}>
                    Adresse du magasin
                  </label>

                  <input
                    class="field"
                    type="text"
                    id="location"
                    name="location"
                    value="<%= @seller.location %>"
                  />
                </div>
               
              <button class="submit-form" type="submit">
                Sauvgarder
              </button>


              </div>


            </form>
          </div>
        </div>
      </div>
</body>
</html>

app/views/pages/register.html.erb
<h1>Pages#register</h1>
<p>Find me in app/views/pages/register.html.erb</p>

app/views/pages/transactions.html.erb
<h1>Pages#transactions</h1>
<p>Find me in app/views/pages/transactions.html.erb</p>

app/views/partials/_invitationCard.html.erb
 <div class='mini-invitation-card' >


        <div class='picture' > 
        <img src="<%= inv.images %>" />
         </div>
        <div class="mini-invitation-card-infos">
            <div class="header">
              <div class='title' >
                <span><%= inv.product %></span>
                
                </div>
              <div class='price' > <%= number_to_currency(inv.price, unit: '', precision: 2 , position: :after)  %>  DA</div>
              </div>
            <div class="descr descr-md"><%= inv.description %> </div>
            <div class="descr descr-sm"><%= inv.description %> </div>
           
        <div class='info' >
         <div  > <%= inv.store_wilaya %> , <%= inv.store_location %></div>
         <div ><%= I18n.l(inv.date, format: "%d, %b %Y")%></div>
        </div>
        <div class="transactions-info" >
          <div class="transaction-info" >
               
               <div class="label" ><i class="fa-solid fa-circle-pause"></i></div>
               <div class="number" >0</div>
           </div>
            <div class="transaction-info" >
               
                <div class="label" ><i class="fa-solid fa-comments-dollar"></i></div>
                <div class="number" >0</div>
            </div>
            <div class="transaction-info" >              
                <div class="label" ><i class="fa-solid fa-square-check"></i></div>
                <div class="number" >0</div>
            </div>
            <div class="transaction-info" >
               
               <div class="label" ><i class="fa-solid fa-rectangle-xmark"></i></div>
               <div class="number" >0</div>
           </div>
          </div>
        </div>
    </div>

app/views/partials/_navbar.html.erb
    <nav class="navigation">
      <a href="/" class="brand-name">
        Home
      </a>
      <div
        class="navigation-menu"
      >
        <ul>
          <li>
            <a
              href="/invitations"
            >
              Annouces
            </a>
          </li>
          <li>
            <a
              href="/new"
            >
              Ajouter Announce
            </a>
          </li>
          <li>
            <a
              
              href="/profile"
            >
            
              Profile
            </a>
          </li>
          <li  >
            <a href="/logout" class="logOut-icon">
                Deconnexion
            </a>
          </li>
        </ul>
      </div>
    </nav>